import Footer from "@/app/components/Footer"
import Header from "@/app/components/Header"
import '@/styles/globals.css'

export const metadata = {
  title: 'User App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body>  
        <Header />
          { children }
        <Footer/>
      </body>
    </html>
  )
}
